<?php
require __DIR__.'/config.php';
$a=$_GET['action']??'';$d=body();
try{
 if($_SERVER['REQUEST_METHOD']!=='GET')verify_csrf($d);
 if($a==='register'){
  $name=trim($d['name']??'');$email=strtolower(trim($d['email']??''));$phone=clean_phone($d['phone']??'');$pass=$d['password']??'';
  if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($phone)<10||strlen($pass)<8)throw new RuntimeException('Enter a valid name, email, phone and password of at least 8 characters.');
  $photo=save_photo($d['photo']??'');$pdo->prepare('INSERT INTO users(name,email,phone,password_hash,photo) VALUES(?,?,?,?,?)')->execute([$name,$email,$phone,password_hash($pass,PASSWORD_DEFAULT),$photo]);$id=(int)$pdo->lastInsertId();
  $code=(string)random_int(100000,999999);$h=password_hash($code,PASSWORD_DEFAULT);$exp=date('Y-m-d H:i:s',time()+600);$q=$pdo->prepare('INSERT INTO verification_codes(user_id,channel,code_hash,expires_at) VALUES(?,?,?,?)');$q->execute([$id,'email',$h,$exp]);$q->execute([$id,'phone',$h,$exp]);$_SESSION['pending']=$id;
  json_out(['ok'=>true,'message'=>'Verification code sent to your email and phone.','demo_code'=>DEMO_VERIFICATION?$code:null]);
 }
 if($a==='verify'){$id=(int)($_SESSION['pending']??0);$code=trim($d['code']??'');$q=$pdo->prepare('SELECT * FROM verification_codes WHERE user_id=? AND used_at IS NULL AND expires_at>NOW() ORDER BY id DESC');$q->execute([$id]);$valid=false;foreach($q as $row)if(password_verify($code,$row['code_hash']))$valid=true;if(!$valid)throw new RuntimeException('Invalid or expired verification code.');$pdo->prepare('UPDATE users SET verified_at=NOW() WHERE id=?')->execute([$id]);$pdo->prepare('UPDATE verification_codes SET used_at=NOW() WHERE user_id=?')->execute([$id]);json_out(['ok'=>true,'message'=>'Account verified. You can now sign in.']);}
 if($a==='login'){$email=strtolower(trim($d['email']??''));$q=$pdo->prepare('SELECT * FROM users WHERE email=?');$q->execute([$email]);$u=$q->fetch();if(!$u||!password_verify($d['password']??'',$u['password_hash']))throw new RuntimeException('Incorrect email or password.');if(!$u['verified_at'])throw new RuntimeException('Verify your account first.');unset($u['password_hash']);$_SESSION['user']=$u;session_regenerate_id(true);json_out(['ok'=>true,'user'=>$u]);}
 if($a==='logout'){need_login();$_SESSION=[];session_destroy();json_out(['ok'=>true]);}
 if($a==='products'){need_login();$q=$pdo->query('SELECT id,sku,name,category,price,stock FROM products WHERE active=1 ORDER BY name');json_out(['ok'=>true,'products'=>$q->fetchAll()]);}
 if($a==='checkout'){$u=need_login();$cart=$d['cart']??[];if(!$cart)throw new RuntimeException('Your cart is empty.');$pdo->beginTransaction();$total=0;$lines=[];foreach($cart as $x){$q=$pdo->prepare('SELECT * FROM products WHERE id=? AND active=1 FOR UPDATE');$q->execute([(int)$x['id']]);$p=$q->fetch();$qty=max(1,(int)$x['qty']);if(!$p||$p['stock']<$qty)throw new RuntimeException('Insufficient stock for a selected item.');$total+=(float)$p['price']*$qty;$lines[]=[$p,$qty];}$receipt='SM'.date('Ymd').strtoupper(bin2hex(random_bytes(3)));$pdo->prepare('INSERT INTO sales(receipt_no,user_id,total,payment_method) VALUES(?,?,?,?)')->execute([$receipt,$u['id'],$total,$d['payment']??'mobile_money']);$sale=(int)$pdo->lastInsertId();foreach($lines as [$p,$qty]){$pdo->prepare('INSERT INTO sale_items(sale_id,product_id,quantity,unit_price) VALUES(?,?,?,?)')->execute([$sale,$p['id'],$qty,$p['price']]);$pdo->prepare('UPDATE products SET stock=stock-? WHERE id=?')->execute([$qty,$p['id']]);}$pdo->prepare('INSERT INTO audit_logs(user_id,action,details,ip_address) VALUES(?,?,?,?)')->execute([$u['id'],'checkout',$receipt,$_SERVER['REMOTE_ADDR']??'']);$pdo->commit();json_out(['ok'=>true,'receipt'=>$receipt,'total'=>$total,'qr_text'=>'SMARTMART|'.$receipt.'|GHS '.number_format($total,2)]);}
 if($a==='admin_save_product'){$u=need_login();if($u['role']!=='admin')json_out(['ok'=>false,'message'=>'Administrator access required.'],403);$id=(int)($d['id']??0);$v=[trim($d['sku']),trim($d['name']),trim($d['category']),max(0,(float)$d['price']),max(0,(int)$d['stock'])];if($id){$v[]=$id;$pdo->prepare('UPDATE products SET sku=?,name=?,category=?,price=?,stock=? WHERE id=?')->execute($v);}else{$pdo->prepare('INSERT INTO products(sku,name,category,price,stock) VALUES(?,?,?,?,?)')->execute($v);}json_out(['ok'=>true]);}
 json_out(['ok'=>false,'message'=>'Unknown request.'],404);
}catch(PDOException $e){if($pdo->inTransaction())$pdo->rollBack();json_out(['ok'=>false,'message'=>$e->getCode()==='23000'?'Email, phone or product code already exists.':'Database request failed.'],400);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();json_out(['ok'=>false,'message'=>$e->getMessage()],400);}
