<?php require __DIR__.'/config.php'; $u=user(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SmartMart Self Checkout</title><link rel="stylesheet" href="assets/app.css"></head><body data-user='<?=htmlspecialchars(json_encode($u),ENT_QUOTES)?>' data-csrf="<?=csrf()?>">
<header><div class="brand">🛒 <b>SmartMart</b><small>Secure Self Checkout</small></div><button id="logout" class="ghost" hidden>Sign out</button></header>
<main>
<section id="welcome" class="hero"><div><span class="tag">Fast • Safe • Cashless</span><h1>Shop, scan and pay—your way.</h1><p>Create a verified account using your email, phone number and live picture, then complete checkout in minutes.</p></div>
<div class="auth card"><div class="tabs"><button data-tab="login" class="active">Sign in</button><button data-tab="register">Register</button><button data-tab="verify">Verify</button></div>
<form id="login" class="panel active"><input name="email" type="email" placeholder="Email address" required><input name="password" type="password" placeholder="Password" required><button>Sign in securely</button></form>
<form id="register" class="panel"><input name="name" placeholder="Full name" required><input name="email" type="email" placeholder="Email address" required><input name="phone" type="tel" placeholder="Phone, e.g. +233..." required><input name="password" type="password" minlength="8" placeholder="Password (8+ characters)" required><video id="camera" autoplay playsinline></video><canvas id="snapshot" hidden></canvas><div class="row"><button type="button" id="startCamera" class="ghost">Open camera</button><button type="button" id="takePhoto" class="ghost">Take live picture</button></div><img id="photoPreview" alt="Live photo preview" hidden><input type="hidden" name="photo" required><button>Create verified account</button></form>
<form id="verify" class="panel"><p>Enter the 6-digit code sent to both your email and phone.</p><input name="code" inputmode="numeric" maxlength="6" placeholder="Verification code" required><button>Verify account</button></form><p id="authMsg" class="message"></p></div></section>
<section id="shop" hidden><div class="dashboard-head"><div><h1>Self Checkout</h1><p id="hello"></p></div><div class="status">● Identity verified</div></div><div class="layout"><div><input id="search" class="search" placeholder="Search name, category or product code"><div id="products" class="products"></div></div><aside class="card cart"><h2>Your basket</h2><div id="cartLines"></div><div class="total"><span>Total</span><b id="total">GH₵0.00</b></div><select id="payment"><option value="mobile_money">Mobile Money</option><option value="card">Bank Card</option><option value="cashier">Pay at Cashier</option></select><button id="checkout">Pay securely</button><div id="receipt" hidden><h3>Payment successful</h3><img id="qr" alt="Receipt QR code"><p id="receiptText"></p><button onclick="print()" class="ghost">Print receipt</button></div></aside></div>
<section id="admin" hidden class="card"><h2>Product & Stock Management</h2><form id="productForm" class="admin-grid"><input name="sku" placeholder="SKU" required><input name="name" placeholder="Product name" required><input name="category" placeholder="Category"><input name="price" type="number" step="0.01" placeholder="Price" required><input name="stock" type="number" placeholder="Stock" required><button>Save product</button></form></section></section>
</main><footer>SmartMart © 2026 • Prices in Ghana cedis • Protected customer verification</footer><script src="assets/app.js"></script></body></html>
