CREATE TABLE users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL,
 full_name VARCHAR(120) NOT NULL, role ENUM('user','admin') NOT NULL DEFAULT 'user', verified_at DATETIME NULL,
 verify_hash CHAR(64) NULL, verify_expires DATETIME NULL, otp_hash CHAR(64) NULL, otp_expires DATETIME NULL,
 failed_logins TINYINT UNSIGNED NOT NULL DEFAULT 0, locked_until DATETIME NULL, qr_token CHAR(64) UNIQUE NOT NULL,
 photo_path VARCHAR(255) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE transactions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, amount DECIMAL(12,2) NOT NULL,
 beneficiary VARCHAR(120) NOT NULL, risk_score TINYINT UNSIGNED NOT NULL, risk_level VARCHAR(12) NOT NULL,
 risk_reasons TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, event VARCHAR(80) NOT NULL,
 ip_hash CHAR(64) NOT NULL, details VARCHAR(255) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(user_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
